/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Organization.Organization;
import Business.Organization.Organization.OrgType;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nitis
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private OrganizationDirectory organizationDirectory;

    public ManageOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        populateTable();
        populateCombo();
    }

    private void populateCombo() {
        cbOrgType.removeAllItems();
        for (OrgType type : Organization.OrgType.values()) {
            if (!type.getValue().equals(OrgType.Admin.getValue()) && !type.getValue().equals(OrgType.FosterCare.getValue()) && !type.getValue().equals(OrgType.Education.getValue())) {
                cbOrgType.addItem(type);
            }
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrg.getModel();
        model.setRowCount(0);

        for (Organization organization : organizationDirectory.getOrganizationList()) {
            Object[] row = new Object[1];
            row[0] = organization;

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblScrollPane = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        cbOrgType = new javax.swing.JComboBox();
        lblOrgType = new javax.swing.JLabel();
        btnDeleteOrganization = new javax.swing.JButton();
        btnAddOrganization1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrg.setMinimumSize(new java.awt.Dimension(375, 0));
        tblScrollPane.setViewportView(tblOrg);
        if (tblOrg.getColumnModel().getColumnCount() > 0) {
            tblOrg.getColumnModel().getColumn(0).setResizable(false);
        }

        add(tblScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 180));

        cbOrgType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrgType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrgTypeActionPerformed(evt);
            }
        });
        add(cbOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 160, -1));

        lblOrgType.setText("Organization Type:");
        add(lblOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, 20));

        btnDeleteOrganization.setText("Delete Organization");
        btnDeleteOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrganizationActionPerformed(evt);
            }
        });
        add(btnDeleteOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, 30));

        btnAddOrganization1.setText("Add Organization");
        btnAddOrganization1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrganization1ActionPerformed(evt);
            }
        });
        add(btnAddOrganization1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, 30));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manage Organization");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 280, 26));
    }// </editor-fold>//GEN-END:initComponents

    private void cbOrgTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrgTypeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cbOrgTypeActionPerformed

    private void btnDeleteOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrganizationActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrg.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the Organization?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Organization o = (Organization) tblOrg.getValueAt(selectedRow, 0);
                organizationDirectory.deleteOrganization(o);
                populateTable();
                JOptionPane.showMessageDialog(null, "Organization deleted successfully", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteOrganizationActionPerformed

    private void btnAddOrganization1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrganization1ActionPerformed
        // TODO add your handling code here:
        OrgType type = (OrgType) cbOrgType.getSelectedItem();
        System.out.println(type.name());
        for (Organization organization : organizationDirectory.getOrganizationList()) {
            if(organization.getName().equals(type.name()+" Organization")){
                JOptionPane.showMessageDialog(null, "Organization already exists", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }     
        organizationDirectory.createOrganization(type);
        populateTable();
    }//GEN-LAST:event_btnAddOrganization1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrganization1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteOrganization;
    private javax.swing.JComboBox cbOrgType;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblOrgType;
    private javax.swing.JTable tblOrg;
    private javax.swing.JScrollPane tblScrollPane;
    // End of variables declaration//GEN-END:variables
}
