/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EmployeeViewArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.GuestWorkArea.HelplineJPanel;
import UserInterface.GuestWorkArea.RaiseIssueJPanel;
import UserInterface.GuestWorkArea.ViewNGOJPanel;
import UserInterface.GuestWorkArea.ViewRehabJPanel;
import UserInterface.ManagerWorkArea.ProjectsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rugved
 */
public class EmployeeViewAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    
    /**
     * Creates new form EmployeeViewAreaJPanel
     */
    public EmployeeViewAreaJPanel(JPanel userProcessContainer, EcoSystem system, DB4OUtil dB4OUtil, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNgoList = new javax.swing.JButton();
        btnRaiseIssue = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        btnProjects = new javax.swing.JButton();
        btnHelpline = new javax.swing.JButton();
        btnViewResolved = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRehabList = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNgoList.setText("NGOs of EcoSystem");
        btnNgoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgoListActionPerformed(evt);
            }
        });
        add(btnNgoList, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 115, 251, -1));

        btnRaiseIssue.setText("Raise Issue");
        btnRaiseIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseIssueActionPerformed(evt);
            }
        });
        add(btnRaiseIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 251, -1));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("View Area");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 250, 27));

        btnProjects.setText("Projects");
        btnProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectsActionPerformed(evt);
            }
        });
        add(btnProjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 250, -1));

        btnHelpline.setText("Helpline");
        btnHelpline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelplineActionPerformed(evt);
            }
        });
        add(btnHelpline, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 251, -1));

        btnViewResolved.setText("View Resolved Issue Statistics");
        btnViewResolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewResolvedActionPerformed(evt);
            }
        });
        add(btnViewResolved, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 251, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 130, 160));

        btnRehabList.setText("Rehabs of EcoSystem");
        btnRehabList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRehabListActionPerformed(evt);
            }
        });
        add(btnRehabList, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 251, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNgoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgoListActionPerformed
        // TODO add your handling code here:
        CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewNGOJPanel vnjp = new ViewNGOJPanel(userProcessContainer, system);
        userProcessContainer.add("vnjp",vnjp);
        cardLayout.next(userProcessContainer); 
    }//GEN-LAST:event_btnNgoListActionPerformed

    private void btnRaiseIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseIssueActionPerformed
        // TODO add your handling code here:
        CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();      
        RaiseIssueJPanel rijp = new RaiseIssueJPanel(userProcessContainer, userAccount, system); 
        userProcessContainer.add("rijp",rijp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnRaiseIssueActionPerformed

    private void btnProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectsActionPerformed
        // TODO add your handling code here:
        CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();
        ProjectViewJPanel pvjp = new ProjectViewJPanel(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("pvjp",pvjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnProjectsActionPerformed

    private void btnHelplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelplineActionPerformed
        // TODO add your handling code here:
        CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();
        HelplineJPanel hjp = new HelplineJPanel(userProcessContainer);
        userProcessContainer.add("hjp",hjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnHelplineActionPerformed

    private void btnViewResolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResolvedActionPerformed
        // TODO add your handling code here:
        CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewResolvedIssuesStatisticsJPanel vrisjp = new ViewResolvedIssuesStatisticsJPanel(userProcessContainer, system, userAccount, enterprise);
        userProcessContainer.add("vrisjp",vrisjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewResolvedActionPerformed

    private void btnRehabListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRehabListActionPerformed
        // TODO add your handling code here:
        CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewRehabJPanel fghj = new ViewRehabJPanel(userProcessContainer, system);
        userProcessContainer.add("fghj",fghj);
        cardLayout.next(userProcessContainer); 
    }//GEN-LAST:event_btnRehabListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelpline;
    private javax.swing.JButton btnNgoList;
    private javax.swing.JButton btnProjects;
    private javax.swing.JButton btnRaiseIssue;
    private javax.swing.JButton btnRehabList;
    private javax.swing.JButton btnViewResolved;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
