/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GuestWorkArea;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rugved
 */
public class RaiseIssueJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;

    /**
     * Creates new form RaiseIssueJPanel
     */
    public RaiseIssueJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btnChildLabour = new javax.swing.JButton();
        btnAdoptionRehab = new javax.swing.JButton();
        btnDonation = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Raise An Issue");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 180, 26));

        btnChildLabour.setText("Child Labour Issue");
        btnChildLabour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChildLabourActionPerformed(evt);
            }
        });
        add(btnChildLabour, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 182, -1));

        btnAdoptionRehab.setText("Child Adoption");
        btnAdoptionRehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptionRehabActionPerformed(evt);
            }
        });
        add(btnAdoptionRehab, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 182, -1));

        btnDonation.setText("Donation of Basic Amenities");
        btnDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationActionPerformed(evt);
            }
        });
        add(btnDonation, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 182, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnChildLabourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChildLabourActionPerformed

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueWorkRequestJPanel rirwjp = new RaiseIssueWorkRequestJPanel(userProcessContainer, userAccount, "Child Labour", system);
        userProcessContainer.add("rirwjp", rirwjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnChildLabourActionPerformed

    private void btnAdoptionRehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptionRehabActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueWorkRequestJPanel rirwjp = new RaiseIssueWorkRequestJPanel(userProcessContainer, userAccount, "Child Adoption", system);
        userProcessContainer.add("rirwjp", rirwjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdoptionRehabActionPerformed

    private void btnDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueWorkRequestJPanel rirwjp = new RaiseIssueWorkRequestJPanel(userProcessContainer, userAccount, "Donation of Basic Amenities", system);
        userProcessContainer.add("rirwjp", rirwjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnDonationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdoptionRehab;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChildLabour;
    private javax.swing.JButton btnDonation;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
