/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ApplicantWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import UserInterface.GuestWorkArea.HelplineJPanel;
import UserInterface.GuestWorkArea.ViewNGOJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rugved
 */
public class ApplicantViewAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;

    /**
     * Creates new form ApplicantViewAreaJPanel
     */
    public ApplicantViewAreaJPanel(JPanel userProcessContainer, EcoSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btnNgoList = new javax.swing.JButton();
        btnHelpline = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Applicant view Area");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 250, 27));

        btnNgoList.setText("NGOs of EcoSystem");
        btnNgoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgoListActionPerformed(evt);
            }
        });
        add(btnNgoList, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 251, -1));

        btnHelpline.setText("Helpline");
        btnHelpline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelplineActionPerformed(evt);
            }
        });
        add(btnHelpline, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 251, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNgoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgoListActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewNGOJPanel vnjp = new ViewNGOJPanel(userProcessContainer, system);
        userProcessContainer.add("vnjp", vnjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnNgoListActionPerformed

    private void btnHelplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelplineActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        HelplineJPanel hjp = new HelplineJPanel(userProcessContainer);
        userProcessContainer.add("hjp", hjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnHelplineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelpline;
    private javax.swing.JButton btnNgoList;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
